name: CI

on:
  push:
    branches:
      - main

jobs:
  verify:
    if: ${{ !contains(github.event.head_commit.message, '[skip release ci]') }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    uses: ./.github/workflows/_verify.yml
    with:
      node-version: ${{ matrix.node-version }}
