name: CI

on:
  push:
    branches:
      - main

jobs:
  verify:
    strategy:
      fail-fast: false
      matrix:
        node-version: [18, 20, 22]
    uses: ./.github/workflows/_verify.yml
    with:
      node-version: ${{ matrix.node-version }}
